
INSERT INTO AUTHORIZEDUSER (ID, USERLOGIN, USERPASSWORD, USERROLE, USERNAME, USERSURNAME, USERREGISTRATIONDATE, USERSTATUS, USERADDRESS, USERNUMBER) VALUES ('0', 'ADMIN@gmail.com', '$2a$10$x.MxMBwMxr8aaPtdEIyd0uTkZ6986p9JmrBT3t1yO5V/cRf9ArJom', 'ADMIN', 'ADMIN', 'ADMIN', TO_DATE('1981-05-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'AUTHORIZED', 'ADMINSTREET', 'ADMINNUMBER');
INSERT INTO AUTHORIZEDUSER (ID, USERLOGIN, USERPASSWORD, USERROLE, USERNAME, USERSURNAME, USERREGISTRATIONDATE, USERSTATUS, USERADDRESS, USERNUMBER) VALUES ('1', 'MANAGER@gmail.com', '$2a$10$x.MxMBwMxr8aaPtdEIyd0uTkZ6986p9JmrBT3t1yO5V/cRf9ArJom', 'MANAGER', 'MANAGER', 'MANAGER', TO_DATE('1982-05-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'AUTHORIZED', 'MANAGERSTREET', 'MANAGERNUMBER');
INSERT INTO AUTHORIZEDUSER (ID, USERLOGIN, USERPASSWORD, USERROLE, USERNAME, USERSURNAME, USERREGISTRATIONDATE, USERSTATUS, USERADDRESS, USERNUMBER) VALUES ('2', 'COURIER@gmail.com', '$2a$10$x.MxMBwMxr8aaPtdEIyd0uTkZ6986p9JmrBT3t1yO5V/cRf9ArJom', 'COURIER', 'COURIER', 'COURIER', TO_DATE('1983-05-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'AUTHORIZED', 'COURIERSTREET', 'COURIERNUMBER');
--
INSERT INTO GENRE (ID, GENRENAME) VALUES ('0', 'FANTASY');
INSERT INTO GENRE (ID, GENRENAME) VALUES ('1', 'SCI-FI');
--
INSERT INTO COVERTYPE (ID, COVERTYPENAME) VALUES ('0', 'HARD');
INSERT INTO COVERTYPE (ID, COVERTYPENAME) VALUES ('1', 'SOFT');
--
INSERT INTO AUTHOR (ID, AUTHORNAME) VALUES ('0', 'PUSHKIN');
INSERT INTO AUTHOR (ID, AUTHORNAME) VALUES ('1', 'SHEVCHENKO');
--
INSERT INTO LANGUAGE (ID, LANGUAGENAME) VALUES ('0', 'ENGLISH');
INSERT INTO LANGUAGE (ID, LANGUAGENAME) VALUES ('1', 'UKRAINIAN');
--
INSERT INTO PUBLISHER (ID, PUBLISHERNAME) VALUES ('0', 'PUBLISHER1');
INSERT INTO PUBLISHER (ID, PUBLISHERNAME) VALUES ('1', 'PUBLISHER2');
--
INSERT INTO PRODUCT (ID, PRODUCTNAME, PRODUCTAMOUNT, PRODUCTPRICE, PRODUCTDISCOUNT, PRODUCTDATE,
                     PRODUCTPICT, PRODUCTDESCRIPTION, PRODUCTSTATUS, GENRE, COVERTYPE, AUTHOR, LANGUAGE, PUBLISHER)
VALUES ('0', 'BIGBOOK', '100', '100', '0', TO_DATE('2021-06-02 23:39:34', 'YYYY-MM-DD HH24:MI:SS'),
        'TESTURL', 'TESTDESC', 'T', '0', '0', '0', '0', '0');
INSERT INTO PRODUCT (ID, PRODUCTNAME, PRODUCTAMOUNT, PRODUCTPRICE, PRODUCTDISCOUNT, PRODUCTDATE,
                     PRODUCTPICT, PRODUCTDESCRIPTION, PRODUCTSTATUS, GENRE, COVERTYPE, AUTHOR, LANGUAGE, PUBLISHER)
VALUES ('1', 'BIGBOOK', '100', '100', '0', TO_DATE('2021-06-02 23:39:34', 'YYYY-MM-DD HH24:MI:SS'),
        'TESTURL', 'TESTDESC', 'T', '1', '1', '1', '1', '1');
INSERT INTO PRODUCT (ID, PRODUCTNAME, PRODUCTAMOUNT, PRODUCTPRICE, PRODUCTDISCOUNT, PRODUCTDATE,
                     PRODUCTPICT, PRODUCTDESCRIPTION, PRODUCTSTATUS, GENRE, COVERTYPE, AUTHOR, LANGUAGE, PUBLISHER)
VALUES ('2', 'Harry Potter', '20', '200', '0', TO_DATE('2021-06-02 23:39:34', 'YYYY-MM-DD HH24:MI:SS'),
        'TESTURL', 'TESTDESC', 'T', '1', '0', '1', '1', '1');

--


