name: "Verify type labels of a pull request"

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]

jobs:
  label-verify:
    runs-on: ubuntu-18.04
    steps:
      - uses: zwaldowski/match-label-action@v2
        with:
          allowed_multiple: 'type:fix, type:features, type:documentation, type:tests, type:config'